services:
  - type: web
    name: catmash-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
    autoDeploy: true
    healthCheckPath: /api/cats
    region: oregon
